url: https://traefik.github.io/charts/traefik/traefik-20.3.0.tgz
packageVersion: 1
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
